Repository WildCodeSchool-2024-09/toulouse-p2-pokemon-arena, pull requests merged in 2024-11, with the labels that each got.

#3 feat: change title
  client/src/App.tsx
Labels: CORRECTIONS_DONE, REVIEWD

#7 S0 us00/fix command
  client/package.json
  client/src/App.tsx
  client/src/main.tsx
Labels: REVIEWD

#4 fix: change paragraph
  client/src/App.tsx
Labels: CHANGE_REQUESTED, REVIEWD

#6 feat: modify and add h2
  client/src/App.tsx
Labels: CORRECTIONS_DONE, REVIEWD

#5 feat: change title content
  client/src/App.tsx
Labels: CONFLICTS_RESOLVED, REVIEWD

#8 feat: create the HTML for the home page
  client/index.html
  client/package.json
  client/public/icone-pokemon-arena.ico
  client/public/vite.svg
  client/src/App.css
  client/src/App.tsx
  client/src/assets/images/background.webp
  client/src/assets/images/logo-pokemon-arena.png
  client/src/main.css
  client/src/main.tsx
  client/src/pages/Home.tsx
  client/src/styles/Home.css
Labels: CONFLICTS, REVIEWD

#10 fix: correct css of the page
  client/src/App.tsx
  client/src/components/CustomizedSlider.tsx
  client/src/styles/BattleSettings.css
Labels: REVIEWD

#11 S1 us05/pokedex search page
  client/index.html
  client/src/App.tsx
  client/src/components/PokemonMiniature.tsx
  client/src/main.tsx
  client/src/pages/PokedexSearch.tsx
  client/src/services/getApi.ts
  client/src/styles/Home.css
  client/src/styles/PokedexSearch.css
  client/src/styles/PokemonMiniature.css
  client/src/types/type.ts
Labels: CONFLICTS_RESOLVED, REVIEWD

#12 S1US03/create button
  client/index.html
  client/src/assets/images/Pokemon-removebg-preview 1.png
  client/src/assets/images/pokemon-pokedex-button.svg
  client/src/pages/Home.tsx
  client/src/styles/Home.css
Labels: REVIEWD

#13 S1 us04/search bar
  client/src/App.css
  client/src/pages/PokedexSearch.tsx
  client/src/services/getApi.ts
  client/src/styles/PokedexSearch.css
  client/src/styles/PokemonMiniature.css
  client/src/types/type.ts
Labels: REVIEWD

#14 style: add of a margin for the text
  client/src/styles/BattleSettings.css
Labels: REVIEWD

#15 style: add some style to the search-bar
  client/src/assets/images/loupe.svg
  client/src/pages/PokedexSearch.tsx
  client/src/styles/PokedexSearch.css
Labels: REVIEWD

#17 S2 us16/pokedex pokemon details navigation arrows
  client/src/pages/PokedexDetails.tsx
  client/src/styles/PokedexDetails.css
Labels: REVIEWD

#18 feat: create the winner page with buttons to navigate
  client/src/assets/images/home.svg
  client/src/assets/images/restart.svg
  client/src/main.tsx
  client/src/pages/Winner.tsx
  client/src/styles/Winner.css
Labels: REVIEWD

#19 S2 us14/pokedex pokemon details navigation tabs
  client/src/App.css
  client/src/assets/images/picto_musique_blanc.svg
  client/src/assets/images/picto_musique_contour_blanc.svg
  client/src/assets/images/picto_musique_fond_blanc.svg
  client/src/components/PokemonNavSpecifications.tsx
  client/src/components/PokemonNavStats.tsx
  client/src/components/StatsBar.tsx
  client/src/main.tsx
  client/src/pages/PokedexDetails.tsx
  client/src/pages/Winner.tsx
  client/src/styles/PokedexDetails.css
  client/src/styles/Winner.css
  client/src/types/type.ts
Labels: CORRECTIONS_DONE, REVIEWED

#20 S2 us07/battle page
  client/package.json
  client/src/assets/images/logo_VS-removebg-preview 1.svg
  client/src/components/CustomizedSlider.tsx
  client/src/components/PokemonBattleCard.tsx
  client/src/context/BattleProvider.tsx
  client/src/main.tsx
  client/src/pages/Battle.tsx
  client/src/pages/BattleSettings.tsx
  client/src/pages/NextRound.tsx
  client/src/pages/PokedexDetails.tsx
  client/src/services/battleCardBackgroundColor.ts
  client/src/services/getApi.ts
  client/src/styles/Battle.css
  client/src/styles/NextRound.css
  client/src/styles/PokemonBattleCard.css
  client/src/types/type.ts
  package-lock.json
Labels: REVIEWED

#21 S2 us11/status turnament
  client/src/components/TurnamentStatus.tsx
  client/src/main.tsx
  client/src/pages/Battle.tsx
  client/src/pages/PokedexSearch.tsx
  client/src/styles/BattleSettings.css
  client/src/styles/PokedexSearch.css
  client/src/styles/PokemonBattleCard.css
  client/src/styles/TurnamentStatus.css
Labels: REVIEWED

#22 S2 us08/pokemon battle winner page
  client/src/components/CustomizedSlider.tsx
  client/src/components/PokemonBattleCard.tsx
  client/src/components/TurnamentStatus.tsx
  client/src/contexts/BattleProvider.tsx
  client/src/main.tsx
  client/src/pages/Battle.tsx
  client/src/pages/BattleSettings.tsx
  client/src/pages/Home.tsx
  client/src/pages/NextRound.tsx
  client/src/pages/Winner.tsx
  client/src/services/battleCardBackgroundColor.ts
  client/src/styles/BattleSettings.css
  client/src/styles/PokedexDetails.css
  client/src/styles/PokedexSearch.css
  client/src/styles/Winner.css
  client/src/types/type.ts
Labels: REVIEWED

#23 style: add style to the card battle
  client/src/components/PokemonBattleCard.tsx
  client/src/components/TournamentStatus.tsx
  client/src/pages/Battle.tsx
  client/src/services/battleCardBackgroundColor.ts
  client/src/styles/Battle.css
  client/src/styles/PokemonBattleCard.css
  client/src/types/type.ts
Labels: REVIEWED

#24 S2 us10/battle filters
  client/package.json
  client/src/components/MultipleSelectChip.tsx
  client/src/components/PokemonBattleCard.tsx
  client/src/components/PokemonMiniature.tsx
  client/src/components/SettingFilter.tsx
  client/src/contexts/BattleProvider.tsx
  client/src/main.tsx
  client/src/pages/Battle.tsx
  client/src/pages/BattleSettings.tsx
  client/src/pages/PokedexDetails.tsx
  client/src/pages/PokedexSearch.tsx
  client/src/pages/Winner.tsx
  client/src/styles/BattleSettings.css
  client/src/styles/PokedexSearch.css
  client/src/styles/PokemonBattleCard.css
  client/src/styles/SettingFilter.css
  client/src/types/type.ts
  package-lock.json
Labels: CORRECTIONS_DONE, REVIEWED

#25 S3 us20/id modale battle
  client/src/components/Pokeball.tsx
  client/src/pages/Home.tsx
  client/src/pages/PokedexDetails.tsx
  client/src/styles/Home.css
  client/src/styles/Pokeball.css
Labels: REVIEWED

#26 feat: add of the opening-animation
  client/src/assets/images/Pokemon-removebg-preview 1.png
  client/src/components/Pokeball.tsx
  client/src/styles/Home.css
  client/src/styles/Pokeball.css
Labels: REVIEWED

#27 S3 us18/page home responsive
  client/src/components/TournamentStatus.tsx
  client/src/pages/Battle.tsx
  client/src/pages/Home.tsx
  client/src/styles/Battle.css
  client/src/styles/Home.css
  client/src/styles/Pokeball.css
  client/src/styles/PokemonBattleCard.css
  client/src/styles/TournamentStatus.css
Labels: CORRECTIONS_DONE, REVIEWED

#28 S2 us10/battle filters
  client/src/assets/images/down-white.svg
  client/src/assets/images/down.svg
  client/src/assets/images/up-white.svg
  client/src/assets/images/up.svg
  client/src/components/GenerationTypeFilter.tsx
  client/src/components/MultipleSelectChip.tsx
  client/src/components/SettingFilter.tsx
  client/src/pages/BattleSettings.tsx
  client/src/services/battleCardBackgroundColor.ts
  client/src/styles/BattleSettings.css
  client/src/styles/GenerationTypeFilter.css
  client/src/styles/SettingFilter.css
  client/src/types/type.ts
Labels: CORRECTIONS_DONE, REVIEWED

#29 feat: modification background
  client/src/App.css
  client/src/styles/BattleSettings.css
  client/src/styles/Home.css
  client/src/styles/PokedexSearch.css
Labels: REVIEWED

#30 S3 us13/pokedex filter
  client/src/components/GenerationTypeFilter.tsx
  client/src/components/SettingFilter.tsx
  client/src/contexts/BattleProvider.tsx
  client/src/pages/BattleSettings.tsx
  client/src/pages/PokedexSearch.tsx
  client/src/pages/Winner.tsx
  client/src/services/arrays.ts
  client/src/services/utils.ts
  client/src/types/type.ts
Labels: REVIEWED

#31 S3 us18/pokedex details page responsive
  client/src/pages/PokedexDetails.tsx
  client/src/styles/PokedexDetails.css
Labels: REVIEWED

#33 S3 us18/page home responsive
  client/public/icone-pokemon-arena.ico
  client/src/components/Pokeball.tsx
  client/src/styles/Battle.css
  client/src/styles/Pokeball.css
  client/src/styles/PokemonBattleCard.css
Labels: REVIEWED

#34 S3 us18/pokedex details page responsive
  client/public/icone-pokemon-arena.ico
  client/src/styles/BattleSettings.css
  client/src/styles/GenerationTypeFilter.css
  client/src/styles/Home.css
  client/src/styles/NextRound.css
  client/src/styles/Winner.css
Labels: REVIEWED

#35 S3 us22/user experience
  client/src/components/PokemonBattleCard.tsx
  client/src/contexts/BattleProvider.tsx
  client/src/pages/Battle.tsx
  client/src/pages/NextRound.tsx
  client/src/pages/Winner.tsx
  client/src/styles/Winner.css
  client/src/types/type.ts
Labels: REVIEWED

#36 S3 us18/loading
  client/src/App.tsx
  client/src/components/Loading.tsx
  client/src/components/PokemonBattleCard.tsx
  client/src/contexts/BattleProvider.tsx
  client/src/contexts/DataProvider.tsx
  client/src/main.tsx
  client/src/pages/BattleSettings.tsx
  client/src/pages/PokedexDetails.tsx
  client/src/pages/PokedexSearch.tsx
  client/src/styles/GenerationTypeFilter.css
  client/src/styles/Loading.css
  client/src/styles/PokedexSearch.css
  client/src/types/type.ts
Labels: REVIEWED

#37 S3 us22/user experience
  client/src/components/CustomizedSlider.tsx
  client/src/components/Loading.tsx
  client/src/components/Pokeball.tsx
  client/src/components/Scroll.tsx
  client/src/pages/Home.tsx
  client/src/pages/PokedexSearch.tsx
  client/src/styles/BattleSettings.css
  client/src/styles/Pokeball.css
  client/src/styles/PokedexDetails.css
  client/src/styles/PokedexSearch.css
Labels: REVIEWED

#38 S3 us18/pokedex details page responsive
  client/src/components/MouseFollower.tsx
  client/src/main.tsx
  client/src/pages/Winner.tsx
Labels: REVIEWED

#39 S3 us22/user experience
  client/src/components/PokemonBattleCard.tsx
  client/src/pages/Home.tsx
  client/src/pages/PokedexDetails.tsx
  client/src/pages/Winner.tsx
  client/src/styles/BattleSettings.css
  client/src/styles/Home.css
  client/src/styles/NextRound.css
  client/src/styles/PokedexDetails.css
  client/src/styles/PokedexSearch.css
  client/src/styles/PokemonBattleCard.css
  client/src/styles/SettingFilter.css
  client/src/styles/Winner.css
Labels: REVIEWED

#40 S3 us22/user experience
  client/src/pages/Winner.tsx
  client/src/styles/Winner.css
Labels: REVIEWED

#42 fix: manage error battle
  client/src/components/BattleErrorMessage.tsx
  client/src/pages/Battle.tsx
  client/src/styles/BattleErrorMessage.css
Labels: REVIEWED

#43 fix: resolve bug img
  client/src/components/SettingFilter.tsx
Labels: REVIEWED
